// app/_util/data/bakeryMenu.ts
import { MenuType } from "./types";

export const bakeryMenu: MenuType[] = [
	{
		productId: "BA01",
		slug: "croffle",
		productName: "크로플",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "크루아상 생지로 만든 겉바속촉 와플.",
		productPrice: 3000,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA02",
		slug: "tiramisu-roll-cake",
		productName: "티라미수 롤케이크",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "마스카포네 치즈와 커피 시럽이 어우러진 롤케이크.",
		productPrice: 3500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA03",
		slug: "honey-caramel-bread",
		productName: "허니 카라멜 브레드",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "달콤한 허니 카라멜 소스를 듬뿍 올린 브레드.",
		productPrice: 4500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA04",
		slug: "plain-bagel",
		productName: "플레인 베이글",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "담백하고 쫄깃한 식감이 일품인 기본 베이글.",
		productPrice: 2800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA05",
		slug: "cream-cheese-muffin",
		productName: "크림치즈 머핀",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "부드러운 크림치즈가 들어간 달콤한 머핀.",
		productPrice: 3200,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA06",
		slug: "cheese-stuffed-bagel",
		productName: "치즈 베이글",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "고소한 치즈가 듬뿍 들어간 베이글.",
		productPrice: 3500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA07",
		slug: "pretzel",
		productName: "프레첼",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "바삭하고 짭짤한 맛이 매력적인 프레첼.",
		productPrice: 2500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA08",
		slug: "chocolate-croissant",
		productName: "초코 크루아상",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "부드러운 크루아상에 진한 초코가 들어간 빵.",
		productPrice: 3800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA09",
		slug: "garlic-bread",
		productName: "갈릭 브레드",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "마늘과 버터의 풍미가 가득한 빵.",
		productPrice: 3500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "BA10",
		slug: "strawberry-croffle",
		productName: "딸기 크로플",
		productCategory: ["bakery"],
		productType: ["plain"],
		productDescription: "크로플 위에 달콤한 딸기를 올린 메뉴.",
		productPrice: 4000,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
];
