// app/_util/data/beverageMenu.ts
import { MenuType } from "./types";

export const beverageMenu: MenuType[] = [
	{
		productId: "V01",
		slug: "strawberry-flatccino",
		productName: "딸기 플랫치노",
		productCategory: ["beverage"],
		productType: ["ice", "cream"],
		productDescription: "달콤한 딸기와 부드러운 우유가 조화로운 시원한 음료.",
		productPrice: 4500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V02",
		slug: "peach-flatccino",
		productName: "복숭아 플랫치노",
		productCategory: ["beverage"],
		productType: ["ice", "cream"],
		productDescription: "상큼한 복숭아 맛의 시원한 음료.",
		productPrice: 4500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V03",
		slug: "choco-flatccino",
		productName: "초코 플랫치노",
		productCategory: ["beverage"],
		productType: ["ice", "cream"],
		productDescription: "진한 초코 맛의 달콤한 플랫치노.",
		productPrice: 4500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V04",
		slug: "bluelime-flatccino",
		productName: "블루레몬 플랫치노",
		productCategory: ["beverage"],
		productType: ["ice"],
		productDescription: "상큼한 레몬과 청량한 블루 컬러가 돋보이는 플랫치노.",
		productPrice: 4500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V05",
		slug: "grapefruit-tea",
		productName: "자몽차",
		productCategory: ["beverage"],
		productType: ["hot", "ice"],
		productDescription: "자몽의 상큼 쌉쌀한 맛이 살아있는 차.",
		productPrice: 3800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V06",
		slug: "lemon-tea",
		productName: "레몬차",
		productCategory: ["beverage"],
		productType: ["hot", "ice"],
		productDescription: "레몬의 상큼함이 가득한 차.",
		productPrice: 3800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V07",
		slug: "peppermint-tea",
		productName: "페퍼민트 티",
		productCategory: ["beverage"],
		productType: ["hot"],
		productDescription: "상쾌한 페퍼민트 향이 기분 좋은 허브티.",
		productPrice: 3500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V08",
		slug: "milktea",
		productName: "밀크티",
		productCategory: ["beverage"],
		productType: ["hot", "ice"],
		productDescription: "부드러운 우유와 홍차의 완벽한 조화.",
		productPrice: 4200,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V09",
		slug: "greengrape-ade",
		productName: "청포도 에이드",
		productCategory: ["beverage"],
		productType: ["ice"],
		productDescription: "청포도의 상큼함과 탄산이 어우러진 에이드.",
		productPrice: 4200,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "V10",
		slug: "strawberry-yogurt-flatccino",
		productName: "딸기 요거트 플랫치노",
		productCategory: ["beverage"],
		productType: ["ice", "cream"],
		productDescription: "딸기와 요거트의 상큼함이 더해진 시원한 음료.",
		productPrice: 4800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
];
