// app/_util/data/snackMenu.ts
import { MenuType } from "./types";

export const snackMenu: MenuType[] = [
	{
		productId: "S01",
		slug: "ediya-cookie",
		productName: "이디야 쿠키",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "바삭하고 달콤한 기본 쿠키.",
		productPrice: 1500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S02",
		slug: "chocolate-chip-cookie",
		productName: "초코칩 쿠키",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "달콤한 초코칩이 박힌 바삭한 쿠키.",
		productPrice: 1800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S03",
		slug: "almond-biscotti",
		productName: "아몬드 비스코티",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "고소한 아몬드가 씹히는 이탈리아식 쿠키.",
		productPrice: 2000,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S04",
		slug: "cheese-stick",
		productName: "치즈 스틱",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "고소한 치즈가 들어있는 바삭한 스틱.",
		productPrice: 2500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S05",
		slug: "chocolate-bar",
		productName: "초코바",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "진한 초콜릿 맛이 일품인 초코바.",
		productPrice: 2000,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S06",
		slug: "granola-bar",
		productName: "그래놀라 바",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "영양 가득한 그래놀라로 만든 바.",
		productPrice: 2200,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S07",
		slug: "brownie",
		productName: "브라우니",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "쫀득하고 진한 초코맛의 브라우니.",
		productPrice: 3000,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S08",
		slug: "mini-waffle",
		productName: "미니 와플",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "한 입 크기로 즐기는 바삭한 와플.",
		productPrice: 2500,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S09",
		slug: "custard-pie",
		productName: "커스터드 파이",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "부드러운 커스터드 크림이 들어간 파이.",
		productPrice: 2800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
	{
		productId: "S10",
		slug: "caramel-waffle",
		productName: "카라멜 와플",
		productCategory: ["snack"],
		productType: ["plain"],
		productDescription: "달콤한 카라멜이 들어간 와플.",
		productPrice: 2800,
		productImage: "/noImage.jpg",
		productOptions: [],
	},
];
